import Head from "next/head";
import Tetris from "@/components/Tetris/Tetris/Tetris";

export default function Home() {
	return (
		<>
			<Head>
				<title>John Wang Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Tetris />
			</main>
		</>
	);
}
